Initial proposal for static holding site
osgeo-oceania/foss4g-2025-placeholder pull request #1
Opened 2024-09-19 11:56 UTC by hamishcampbell

Provides a responsive landing page with some basic information for the 2025 conference.

2024-09-19 12:06 UTC, nf-s approved these changes
Looks great to me!

2024-09-19 14:59 UTC, nf-s requested changes
Just noticed some small misspellings

2024-09-19 14:59 UTC, nf-s commented on holding-page-static/index.html
> +										<p>OSGeo Oceanaia invites the FOSS4G community to Auckland / Tāmaki Makaurau,
```suggestion
										<p>OSGeo Oceania invites the FOSS4G community to Auckland / Tāmaki Makaurau, 
```

2024-09-19 14:59 UTC, nf-s commented on holding-page-static/index.html
> +											the City of Sales, largest city of New Zealand Aotearoa for FOSS4G 2025.
```suggestion
											the City of Sails, largest city of New Zealand Aotearoa for FOSS4G 2025.
```

2024-09-19 14:59 UTC, nf-s commented on holding-page-static/index.html
> +							the central business district, has excellent public transport and accomodation options.
```suggestion
							the central business district, has excellent public transport and accommodation options.
```

2024-09-19 14:59 UTC, nf-s commented on holding-page-static/index.html
> +							<p>Sign up to our newsletter to recieve updates and information about FOSS4G 2025</p>
```suggestion
							<p>Sign up to our newsletter to receive updates and information about FOSS4G 2025</p>
```

2024-09-19 20:32 UTC, hamishcampbell commented
> Just noticed some small misspellings

Legend, thank you!

2024-09-20 01:45 UTC, nf-s reviewed
Just tested it on my phone - it would be nice to center the "save the date" image. As it zooms into the side on smaller screens
![IMG_6568](https://github.com/user-attachments/assets/a70159c8-45cc-4d10-aecd-8e10718b171b)

2024-09-21 04:36 UTC, hamishcampbell commented
@nf-s good spotting, should be better now

![IMG_9036](https://github.com/user-attachments/assets/aee9f5d6-e9e0-4a6d-9d99-5a22fff1a7e0)

2024-09-21 04:37 UTC, merged